const member = {
    hoTen:'',
    tenDangNhap:'',
    matKhau:'',
    anhDaiDien:'',
    thuDienTu:'',
    gioiTinh:'',
    soThich:'',
    queQuan:'',
    diaChi:'',
    dienThoai:'',
    moTaNgan:'',
}
// mock data
const listMember = [
    {
        hoTen:'Chung Trịnh',
        tenDangNhap:'chungtrinhj',
        matKhau:'123456a@',
        anhDaiDien:'chung.jpg',
        thuDienTu:'chungtrinhj@gmail.com',
        gioiTinh:'Nam',
        soThich:'Bóng đá',
        queQuan:'Thanh hóa',
        diaChi:'25 Vũ Ngọc Phan, Láng hạ',
        dienThoai:'0978611889',
        moTaNgan:'Không có gì',
    },
    {
        hoTen:'Huỳnh Minh Đức',
        tenDangNhap:'minhduc',
        matKhau:'ducminh!@123',
        anhDaiDien:'duc.jpg',
        thuDienTu:'minhduc@gmail.com',
        gioiTinh:'Nam',
        soThich:'Xem phim',
        queQuan:'Hà nội',
        diaChi:'123 ABC',
        dienThoai:'0123123123',
        moTaNgan:'hola',
    },
    {
        hoTen:'Thúy Nga',
        tenDangNhap:'minhduc',
        matKhau:'ducminh!@123',
        anhDaiDien:'duc.jpg',
        thuDienTu:'minhduc@gmail.com',
        gioiTinh:'Nam',
        soThich:'Xem phim',
        queQuan:'Hà nội',
        diaChi:'123 ABC',
        dienThoai:'0123123123',
        moTaNgan:'hola',
    }
]